### ISSUE TITLE
`dev -p` reports default port when custom port is used

### ISSUE THREAD

**Issue by colepeters** [beginner-corp/begin-api#42]
When executing `begin dev -p <CUSTOM PORT>`, the default port (`3333`) is reported in the output, despite the custom port being used.

This issue does **not** occur when using the verbose argument, i.e. `begin dev --port <CUSTOM PORT>`.

Example:

```bash
❯ begin dev -p 3334
  Enhance Styles: CSS generated.
Updated posts.json
env  [ 'dev', '-p', '3334' ]
http://localhost:3333
❤︎ Begin dev server (main-2420e98) ready!
http://localhost:3333
```

**Comment by macdonst** [comment]
This will be fixed by a70c0d11cb2e500913b77423211ec170df7ed341
